//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringsTestService")]
public interface IStringsTestService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsTestService/TestString", ReplyAction="http://tempuri.org/IStringsTestService/TestStringResponse")]
    int TestString(string containee, string container);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringsTestService/TestString", ReplyAction="http://tempuri.org/IStringsTestService/TestStringResponse")]
    System.Threading.Tasks.Task<int> TestStringAsync(string containee, string container);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringsTestServiceChannel : IStringsTestService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringsTestServiceClient : System.ServiceModel.ClientBase<IStringsTestService>, IStringsTestService
{
    
    public StringsTestServiceClient()
    {
    }
    
    public StringsTestServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringsTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringsTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringsTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int TestString(string containee, string container)
    {
        return base.Channel.TestString(containee, container);
    }
    
    public System.Threading.Tasks.Task<int> TestStringAsync(string containee, string container)
    {
        return base.Channel.TestStringAsync(containee, container);
    }
}
